apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: myfirstpod
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myfirstpod
    spec:
      containers:
      - name: myfirstpod
        image: gcr.io/docker-miage/flask-app
        ports:
        - containerPort: 80
