apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: test
spec:
  containers:
  - name: myfirstflask
    image: gcr.io/skilled-index-253808/flask-app 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
